// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Vcd
{
    public static class GetNsxtEdgegatewayBgpConfiguration
    {
        public static Task<GetNsxtEdgegatewayBgpConfigurationResult> InvokeAsync(GetNsxtEdgegatewayBgpConfigurationArgs args, InvokeOptions? options = null)
            => Pulumi.Deployment.Instance.InvokeAsync<GetNsxtEdgegatewayBgpConfigurationResult>("vcd:index/getNsxtEdgegatewayBgpConfiguration:getNsxtEdgegatewayBgpConfiguration", args ?? new GetNsxtEdgegatewayBgpConfigurationArgs(), options.WithDefaults());

        public static Output<GetNsxtEdgegatewayBgpConfigurationResult> Invoke(GetNsxtEdgegatewayBgpConfigurationInvokeArgs args, InvokeOptions? options = null)
            => Pulumi.Deployment.Instance.Invoke<GetNsxtEdgegatewayBgpConfigurationResult>("vcd:index/getNsxtEdgegatewayBgpConfiguration:getNsxtEdgegatewayBgpConfiguration", args ?? new GetNsxtEdgegatewayBgpConfigurationInvokeArgs(), options.WithDefaults());
    }


    public sealed class GetNsxtEdgegatewayBgpConfigurationArgs : global::Pulumi.InvokeArgs
    {
        [Input("edgeGatewayId", required: true)]
        public string EdgeGatewayId { get; set; } = null!;

        [Input("org")]
        public string? Org { get; set; }

        public GetNsxtEdgegatewayBgpConfigurationArgs()
        {
        }
        public static new GetNsxtEdgegatewayBgpConfigurationArgs Empty => new GetNsxtEdgegatewayBgpConfigurationArgs();
    }

    public sealed class GetNsxtEdgegatewayBgpConfigurationInvokeArgs : global::Pulumi.InvokeArgs
    {
        [Input("edgeGatewayId", required: true)]
        public Input<string> EdgeGatewayId { get; set; } = null!;

        [Input("org")]
        public Input<string>? Org { get; set; }

        public GetNsxtEdgegatewayBgpConfigurationInvokeArgs()
        {
        }
        public static new GetNsxtEdgegatewayBgpConfigurationInvokeArgs Empty => new GetNsxtEdgegatewayBgpConfigurationInvokeArgs();
    }


    [OutputType]
    public sealed class GetNsxtEdgegatewayBgpConfigurationResult
    {
        public readonly bool EcmpEnabled;
        public readonly string EdgeGatewayId;
        public readonly bool Enabled;
        public readonly string GracefulRestartMode;
        public readonly int GracefulRestartTimer;
        /// <summary>
        /// The provider-assigned unique ID for this managed resource.
        /// </summary>
        public readonly string Id;
        public readonly string LocalAsNumber;
        public readonly string? Org;
        public readonly int StaleRouteTimer;

        [OutputConstructor]
        private GetNsxtEdgegatewayBgpConfigurationResult(
            bool ecmpEnabled,

            string edgeGatewayId,

            bool enabled,

            string gracefulRestartMode,

            int gracefulRestartTimer,

            string id,

            string localAsNumber,

            string? org,

            int staleRouteTimer)
        {
            EcmpEnabled = ecmpEnabled;
            EdgeGatewayId = edgeGatewayId;
            Enabled = enabled;
            GracefulRestartMode = gracefulRestartMode;
            GracefulRestartTimer = gracefulRestartTimer;
            Id = id;
            LocalAsNumber = localAsNumber;
            Org = org;
            StaleRouteTimer = staleRouteTimer;
        }
    }
}
