// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Vcd
{
    public static class GetOrgLdap
    {
        public static Task<GetOrgLdapResult> InvokeAsync(GetOrgLdapArgs args, InvokeOptions? options = null)
            => Pulumi.Deployment.Instance.InvokeAsync<GetOrgLdapResult>("vcd:index/getOrgLdap:getOrgLdap", args ?? new GetOrgLdapArgs(), options.WithDefaults());

        public static Output<GetOrgLdapResult> Invoke(GetOrgLdapInvokeArgs args, InvokeOptions? options = null)
            => Pulumi.Deployment.Instance.Invoke<GetOrgLdapResult>("vcd:index/getOrgLdap:getOrgLdap", args ?? new GetOrgLdapInvokeArgs(), options.WithDefaults());
    }


    public sealed class GetOrgLdapArgs : global::Pulumi.InvokeArgs
    {
        [Input("orgId", required: true)]
        public string OrgId { get; set; } = null!;

        public GetOrgLdapArgs()
        {
        }
        public static new GetOrgLdapArgs Empty => new GetOrgLdapArgs();
    }

    public sealed class GetOrgLdapInvokeArgs : global::Pulumi.InvokeArgs
    {
        [Input("orgId", required: true)]
        public Input<string> OrgId { get; set; } = null!;

        public GetOrgLdapInvokeArgs()
        {
        }
        public static new GetOrgLdapInvokeArgs Empty => new GetOrgLdapInvokeArgs();
    }


    [OutputType]
    public sealed class GetOrgLdapResult
    {
        public readonly ImmutableArray<Outputs.GetOrgLdapCustomSettingResult> CustomSettings;
        /// <summary>
        /// The provider-assigned unique ID for this managed resource.
        /// </summary>
        public readonly string Id;
        public readonly string LdapMode;
        public readonly string OrgId;

        [OutputConstructor]
        private GetOrgLdapResult(
            ImmutableArray<Outputs.GetOrgLdapCustomSettingResult> customSettings,

            string id,

            string ldapMode,

            string orgId)
        {
            CustomSettings = customSettings;
            Id = id;
            LdapMode = ldapMode;
            OrgId = orgId;
        }
    }
}
