// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Vcd
{
    [VcdResourceType("vcd:index/nsxtEdgegatewayBgpConfiguration:NsxtEdgegatewayBgpConfiguration")]
    public partial class NsxtEdgegatewayBgpConfiguration : global::Pulumi.CustomResource
    {
        /// <summary>
        /// Defines if ECMP (Equal-cost multi-path routing) is enabled
        /// </summary>
        [Output("ecmpEnabled")]
        public Output<bool?> EcmpEnabled { get; private set; } = null!;

        /// <summary>
        /// Edge gateway ID for BGP Configuration
        /// </summary>
        [Output("edgeGatewayId")]
        public Output<string> EdgeGatewayId { get; private set; } = null!;

        /// <summary>
        /// Defines if BGP service is enabled
        /// </summary>
        [Output("enabled")]
        public Output<bool> Enabled { get; private set; } = null!;

        /// <summary>
        /// Graceful restart configuration on Edge Gateway. One of 'DISABLE', 'HELPER_ONLY', 'GRACEFUL_AND_HELPER'
        /// </summary>
        [Output("gracefulRestartMode")]
        public Output<string> GracefulRestartMode { get; private set; } = null!;

        /// <summary>
        /// Maximum time taken (in seconds) for a BGP session to be established after a restart
        /// </summary>
        [Output("gracefulRestartTimer")]
        public Output<int> GracefulRestartTimer { get; private set; } = null!;

        /// <summary>
        /// Autonomous system number
        /// </summary>
        [Output("localAsNumber")]
        public Output<string> LocalAsNumber { get; private set; } = null!;

        /// <summary>
        /// The name of organization to use, optional if defined at provider level. Useful when connected as sysadmin working across
        /// different organizations
        /// </summary>
        [Output("org")]
        public Output<string?> Org { get; private set; } = null!;

        /// <summary>
        /// Maximum time (in seconds) before stale routes are removed when BGP restarts
        /// </summary>
        [Output("staleRouteTimer")]
        public Output<int> StaleRouteTimer { get; private set; } = null!;


        /// <summary>
        /// Create a NsxtEdgegatewayBgpConfiguration resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public NsxtEdgegatewayBgpConfiguration(string name, NsxtEdgegatewayBgpConfigurationArgs args, CustomResourceOptions? options = null)
            : base("vcd:index/nsxtEdgegatewayBgpConfiguration:NsxtEdgegatewayBgpConfiguration", name, args ?? new NsxtEdgegatewayBgpConfigurationArgs(), MakeResourceOptions(options, ""))
        {
        }

        private NsxtEdgegatewayBgpConfiguration(string name, Input<string> id, NsxtEdgegatewayBgpConfigurationState? state = null, CustomResourceOptions? options = null)
            : base("vcd:index/nsxtEdgegatewayBgpConfiguration:NsxtEdgegatewayBgpConfiguration", name, state, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing NsxtEdgegatewayBgpConfiguration resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="state">Any extra arguments used during the lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static NsxtEdgegatewayBgpConfiguration Get(string name, Input<string> id, NsxtEdgegatewayBgpConfigurationState? state = null, CustomResourceOptions? options = null)
        {
            return new NsxtEdgegatewayBgpConfiguration(name, id, state, options);
        }
    }

    public sealed class NsxtEdgegatewayBgpConfigurationArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Defines if ECMP (Equal-cost multi-path routing) is enabled
        /// </summary>
        [Input("ecmpEnabled")]
        public Input<bool>? EcmpEnabled { get; set; }

        /// <summary>
        /// Edge gateway ID for BGP Configuration
        /// </summary>
        [Input("edgeGatewayId", required: true)]
        public Input<string> EdgeGatewayId { get; set; } = null!;

        /// <summary>
        /// Defines if BGP service is enabled
        /// </summary>
        [Input("enabled", required: true)]
        public Input<bool> Enabled { get; set; } = null!;

        /// <summary>
        /// Graceful restart configuration on Edge Gateway. One of 'DISABLE', 'HELPER_ONLY', 'GRACEFUL_AND_HELPER'
        /// </summary>
        [Input("gracefulRestartMode")]
        public Input<string>? GracefulRestartMode { get; set; }

        /// <summary>
        /// Maximum time taken (in seconds) for a BGP session to be established after a restart
        /// </summary>
        [Input("gracefulRestartTimer")]
        public Input<int>? GracefulRestartTimer { get; set; }

        /// <summary>
        /// Autonomous system number
        /// </summary>
        [Input("localAsNumber")]
        public Input<string>? LocalAsNumber { get; set; }

        /// <summary>
        /// The name of organization to use, optional if defined at provider level. Useful when connected as sysadmin working across
        /// different organizations
        /// </summary>
        [Input("org")]
        public Input<string>? Org { get; set; }

        /// <summary>
        /// Maximum time (in seconds) before stale routes are removed when BGP restarts
        /// </summary>
        [Input("staleRouteTimer")]
        public Input<int>? StaleRouteTimer { get; set; }

        public NsxtEdgegatewayBgpConfigurationArgs()
        {
        }
        public static new NsxtEdgegatewayBgpConfigurationArgs Empty => new NsxtEdgegatewayBgpConfigurationArgs();
    }

    public sealed class NsxtEdgegatewayBgpConfigurationState : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Defines if ECMP (Equal-cost multi-path routing) is enabled
        /// </summary>
        [Input("ecmpEnabled")]
        public Input<bool>? EcmpEnabled { get; set; }

        /// <summary>
        /// Edge gateway ID for BGP Configuration
        /// </summary>
        [Input("edgeGatewayId")]
        public Input<string>? EdgeGatewayId { get; set; }

        /// <summary>
        /// Defines if BGP service is enabled
        /// </summary>
        [Input("enabled")]
        public Input<bool>? Enabled { get; set; }

        /// <summary>
        /// Graceful restart configuration on Edge Gateway. One of 'DISABLE', 'HELPER_ONLY', 'GRACEFUL_AND_HELPER'
        /// </summary>
        [Input("gracefulRestartMode")]
        public Input<string>? GracefulRestartMode { get; set; }

        /// <summary>
        /// Maximum time taken (in seconds) for a BGP session to be established after a restart
        /// </summary>
        [Input("gracefulRestartTimer")]
        public Input<int>? GracefulRestartTimer { get; set; }

        /// <summary>
        /// Autonomous system number
        /// </summary>
        [Input("localAsNumber")]
        public Input<string>? LocalAsNumber { get; set; }

        /// <summary>
        /// The name of organization to use, optional if defined at provider level. Useful when connected as sysadmin working across
        /// different organizations
        /// </summary>
        [Input("org")]
        public Input<string>? Org { get; set; }

        /// <summary>
        /// Maximum time (in seconds) before stale routes are removed when BGP restarts
        /// </summary>
        [Input("staleRouteTimer")]
        public Input<int>? StaleRouteTimer { get; set; }

        public NsxtEdgegatewayBgpConfigurationState()
        {
        }
        public static new NsxtEdgegatewayBgpConfigurationState Empty => new NsxtEdgegatewayBgpConfigurationState();
    }
}
