// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Vcd
{
    [VcdResourceType("vcd:index/rightsBundle:RightsBundle")]
    public partial class RightsBundle : global::Pulumi.CustomResource
    {
        /// <summary>
        /// Key used for internationalization
        /// </summary>
        [Output("bundleKey")]
        public Output<string> BundleKey { get; private set; } = null!;

        /// <summary>
        /// Rights bundle description
        /// </summary>
        [Output("description")]
        public Output<string> Description { get; private set; } = null!;

        /// <summary>
        /// Name of rights bundle.
        /// </summary>
        [Output("name")]
        public Output<string> Name { get; private set; } = null!;

        /// <summary>
        /// When true, publishes the rights bundle to all tenants
        /// </summary>
        [Output("publishToAllTenants")]
        public Output<bool> PublishToAllTenants { get; private set; } = null!;

        /// <summary>
        /// Whether this rights bundle is read-only
        /// </summary>
        [Output("readOnly")]
        public Output<bool> ReadOnly { get; private set; } = null!;

        /// <summary>
        /// Set of rights assigned to this rights bundle
        /// </summary>
        [Output("rights")]
        public Output<ImmutableArray<string>> Rights { get; private set; } = null!;

        /// <summary>
        /// Set of tenants to which this rights bundle is published
        /// </summary>
        [Output("tenants")]
        public Output<ImmutableArray<string>> Tenants { get; private set; } = null!;


        /// <summary>
        /// Create a RightsBundle resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public RightsBundle(string name, RightsBundleArgs args, CustomResourceOptions? options = null)
            : base("vcd:index/rightsBundle:RightsBundle", name, args ?? new RightsBundleArgs(), MakeResourceOptions(options, ""))
        {
        }

        private RightsBundle(string name, Input<string> id, RightsBundleState? state = null, CustomResourceOptions? options = null)
            : base("vcd:index/rightsBundle:RightsBundle", name, state, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing RightsBundle resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="state">Any extra arguments used during the lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static RightsBundle Get(string name, Input<string> id, RightsBundleState? state = null, CustomResourceOptions? options = null)
        {
            return new RightsBundle(name, id, state, options);
        }
    }

    public sealed class RightsBundleArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Rights bundle description
        /// </summary>
        [Input("description", required: true)]
        public Input<string> Description { get; set; } = null!;

        /// <summary>
        /// Name of rights bundle.
        /// </summary>
        [Input("name")]
        public Input<string>? Name { get; set; }

        /// <summary>
        /// When true, publishes the rights bundle to all tenants
        /// </summary>
        [Input("publishToAllTenants", required: true)]
        public Input<bool> PublishToAllTenants { get; set; } = null!;

        [Input("rights")]
        private InputList<string>? _rights;

        /// <summary>
        /// Set of rights assigned to this rights bundle
        /// </summary>
        public InputList<string> Rights
        {
            get => _rights ?? (_rights = new InputList<string>());
            set => _rights = value;
        }

        [Input("tenants")]
        private InputList<string>? _tenants;

        /// <summary>
        /// Set of tenants to which this rights bundle is published
        /// </summary>
        public InputList<string> Tenants
        {
            get => _tenants ?? (_tenants = new InputList<string>());
            set => _tenants = value;
        }

        public RightsBundleArgs()
        {
        }
        public static new RightsBundleArgs Empty => new RightsBundleArgs();
    }

    public sealed class RightsBundleState : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Key used for internationalization
        /// </summary>
        [Input("bundleKey")]
        public Input<string>? BundleKey { get; set; }

        /// <summary>
        /// Rights bundle description
        /// </summary>
        [Input("description")]
        public Input<string>? Description { get; set; }

        /// <summary>
        /// Name of rights bundle.
        /// </summary>
        [Input("name")]
        public Input<string>? Name { get; set; }

        /// <summary>
        /// When true, publishes the rights bundle to all tenants
        /// </summary>
        [Input("publishToAllTenants")]
        public Input<bool>? PublishToAllTenants { get; set; }

        /// <summary>
        /// Whether this rights bundle is read-only
        /// </summary>
        [Input("readOnly")]
        public Input<bool>? ReadOnly { get; set; }

        [Input("rights")]
        private InputList<string>? _rights;

        /// <summary>
        /// Set of rights assigned to this rights bundle
        /// </summary>
        public InputList<string> Rights
        {
            get => _rights ?? (_rights = new InputList<string>());
            set => _rights = value;
        }

        [Input("tenants")]
        private InputList<string>? _tenants;

        /// <summary>
        /// Set of tenants to which this rights bundle is published
        /// </summary>
        public InputList<string> Tenants
        {
            get => _tenants ?? (_tenants = new InputList<string>());
            set => _tenants = value;
        }

        public RightsBundleState()
        {
        }
        public static new RightsBundleState Empty => new RightsBundleState();
    }
}
