// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Vcd.Outputs
{

    [OutputType]
    public sealed class GetNetworkRoutedFilterResult
    {
        public readonly string? Ip;
        public readonly ImmutableArray<Outputs.GetNetworkRoutedFilterMetadataResult> Metadatas;
        public readonly string? NameRegex;

        [OutputConstructor]
        private GetNetworkRoutedFilterResult(
            string? ip,

            ImmutableArray<Outputs.GetNetworkRoutedFilterMetadataResult> metadatas,

            string? nameRegex)
        {
            Ip = ip;
            Metadatas = metadatas;
            NameRegex = nameRegex;
        }
    }
}
