// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Vcd.Outputs
{

    [OutputType]
    public sealed class GetNsxtDistributedFirewallRuleResult
    {
        public readonly string Action;
        public readonly ImmutableArray<string> AppPortProfileIds;
        public readonly string Comment;
        public readonly string Description;
        public readonly bool DestinationGroupsExcluded;
        public readonly ImmutableArray<string> DestinationIds;
        public readonly string Direction;
        public readonly bool Enabled;
        public readonly string Id;
        public readonly string IpProtocol;
        public readonly bool Logging;
        public readonly string Name;
        public readonly ImmutableArray<string> NetworkContextProfileIds;
        public readonly bool SourceGroupsExcluded;
        public readonly ImmutableArray<string> SourceIds;

        [OutputConstructor]
        private GetNsxtDistributedFirewallRuleResult(
            string action,

            ImmutableArray<string> appPortProfileIds,

            string comment,

            string description,

            bool destinationGroupsExcluded,

            ImmutableArray<string> destinationIds,

            string direction,

            bool enabled,

            string id,

            string ipProtocol,

            bool logging,

            string name,

            ImmutableArray<string> networkContextProfileIds,

            bool sourceGroupsExcluded,

            ImmutableArray<string> sourceIds)
        {
            Action = action;
            AppPortProfileIds = appPortProfileIds;
            Comment = comment;
            Description = description;
            DestinationGroupsExcluded = destinationGroupsExcluded;
            DestinationIds = destinationIds;
            Direction = direction;
            Enabled = enabled;
            Id = id;
            IpProtocol = ipProtocol;
            Logging = logging;
            Name = name;
            NetworkContextProfileIds = networkContextProfileIds;
            SourceGroupsExcluded = sourceGroupsExcluded;
            SourceIds = sourceIds;
        }
    }
}
