// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Vcd.Outputs
{

    [OutputType]
    public sealed class GetOrgVdcComputeCapacityResult
    {
        public readonly ImmutableArray<Outputs.GetOrgVdcComputeCapacityCpusResult> Cpus;
        public readonly ImmutableArray<Outputs.GetOrgVdcComputeCapacityMemoryResult> Memories;

        [OutputConstructor]
        private GetOrgVdcComputeCapacityResult(
            ImmutableArray<Outputs.GetOrgVdcComputeCapacityCpusResult> cpus,

            ImmutableArray<Outputs.GetOrgVdcComputeCapacityMemoryResult> memories)
        {
            Cpus = cpus;
            Memories = memories;
        }
    }
}
