// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Vcd.Outputs
{

    [OutputType]
    public sealed class NsxtEdgegatewaySubnet
    {
        public readonly ImmutableArray<Outputs.NsxtEdgegatewaySubnetAllocatedIp> AllocatedIps;
        public readonly string Gateway;
        public readonly int PrefixLength;
        public readonly string? PrimaryIp;

        [OutputConstructor]
        private NsxtEdgegatewaySubnet(
            ImmutableArray<Outputs.NsxtEdgegatewaySubnetAllocatedIp> allocatedIps,

            string gateway,

            int prefixLength,

            string? primaryIp)
        {
            AllocatedIps = allocatedIps;
            Gateway = gateway;
            PrefixLength = prefixLength;
            PrimaryIp = primaryIp;
        }
    }
}
