// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Vcd.Outputs
{

    [OutputType]
    public sealed class VappFirewallRulesRule
    {
        public readonly string? DestinationIp;
        public readonly string? DestinationPort;
        public readonly string? DestinationVmId;
        public readonly string? DestinationVmIpType;
        public readonly int? DestinationVmNicId;
        public readonly bool? EnableLogging;
        public readonly bool? Enabled;
        public readonly string? Name;
        public readonly string? Policy;
        public readonly string? Protocol;
        public readonly string? SourceIp;
        public readonly string? SourcePort;
        public readonly string? SourceVmId;
        public readonly string? SourceVmIpType;
        public readonly int? SourceVmNicId;

        [OutputConstructor]
        private VappFirewallRulesRule(
            string? destinationIp,

            string? destinationPort,

            string? destinationVmId,

            string? destinationVmIpType,

            int? destinationVmNicId,

            bool? enableLogging,

            bool? enabled,

            string? name,

            string? policy,

            string? protocol,

            string? sourceIp,

            string? sourcePort,

            string? sourceVmId,

            string? sourceVmIpType,

            int? sourceVmNicId)
        {
            DestinationIp = destinationIp;
            DestinationPort = destinationPort;
            DestinationVmId = destinationVmId;
            DestinationVmIpType = destinationVmIpType;
            DestinationVmNicId = destinationVmNicId;
            EnableLogging = enableLogging;
            Enabled = enabled;
            Name = name;
            Policy = policy;
            Protocol = protocol;
            SourceIp = sourceIp;
            SourcePort = sourcePort;
            SourceVmId = sourceVmId;
            SourceVmIpType = sourceVmIpType;
            SourceVmNicId = sourceVmNicId;
        }
    }
}
