// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Vcd.Outputs
{

    [OutputType]
    public sealed class VappAccessControlSharedWith
    {
        public readonly string AccessLevel;
        public readonly string? GroupId;
        public readonly string? SubjectName;
        public readonly string? UserId;

        [OutputConstructor]
        private VappAccessControlSharedWith(
            string accessLevel,

            string? groupId,

            string? subjectName,

            string? userId)
        {
            AccessLevel = accessLevel;
            GroupId = groupId;
            SubjectName = subjectName;
            UserId = userId;
        }
    }
}
