// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Vcd.Outputs
{

    [OutputType]
    public sealed class VmSizingPolicyCpu
    {
        public readonly string? CoresPerSocket;
        public readonly string? Count;
        public readonly string? LimitInMhz;
        public readonly string? ReservationGuarantee;
        public readonly string? Shares;
        public readonly string? SpeedInMhz;

        [OutputConstructor]
        private VmSizingPolicyCpu(
            string? coresPerSocket,

            string? count,

            string? limitInMhz,

            string? reservationGuarantee,

            string? shares,

            string? speedInMhz)
        {
            CoresPerSocket = coresPerSocket;
            Count = count;
            LimitInMhz = limitInMhz;
            ReservationGuarantee = reservationGuarantee;
            Shares = shares;
            SpeedInMhz = speedInMhz;
        }
    }
}
