// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package vcd

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func LookupExternalNetwork(ctx *pulumi.Context, args *LookupExternalNetworkArgs, opts ...pulumi.InvokeOption) (*LookupExternalNetworkResult, error) {
	var rv LookupExternalNetworkResult
	err := ctx.Invoke("vcd:index/getExternalNetwork:getExternalNetwork", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getExternalNetwork.
type LookupExternalNetworkArgs struct {
	Name string `pulumi:"name"`
}

// A collection of values returned by getExternalNetwork.
type LookupExternalNetworkResult struct {
	Description string `pulumi:"description"`
	// The provider-assigned unique ID for this managed resource.
	Id                             string                             `pulumi:"id"`
	IpScopes                       []GetExternalNetworkIpScope        `pulumi:"ipScopes"`
	Name                           string                             `pulumi:"name"`
	RetainNetInfoAcrossDeployments bool                               `pulumi:"retainNetInfoAcrossDeployments"`
	VsphereNetworks                []GetExternalNetworkVsphereNetwork `pulumi:"vsphereNetworks"`
}

func LookupExternalNetworkOutput(ctx *pulumi.Context, args LookupExternalNetworkOutputArgs, opts ...pulumi.InvokeOption) LookupExternalNetworkResultOutput {
	return pulumi.ToOutputWithContext(context.Background(), args).
		ApplyT(func(v interface{}) (LookupExternalNetworkResult, error) {
			args := v.(LookupExternalNetworkArgs)
			r, err := LookupExternalNetwork(ctx, &args, opts...)
			var s LookupExternalNetworkResult
			if r != nil {
				s = *r
			}
			return s, err
		}).(LookupExternalNetworkResultOutput)
}

// A collection of arguments for invoking getExternalNetwork.
type LookupExternalNetworkOutputArgs struct {
	Name pulumi.StringInput `pulumi:"name"`
}

func (LookupExternalNetworkOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupExternalNetworkArgs)(nil)).Elem()
}

// A collection of values returned by getExternalNetwork.
type LookupExternalNetworkResultOutput struct{ *pulumi.OutputState }

func (LookupExternalNetworkResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupExternalNetworkResult)(nil)).Elem()
}

func (o LookupExternalNetworkResultOutput) ToLookupExternalNetworkResultOutput() LookupExternalNetworkResultOutput {
	return o
}

func (o LookupExternalNetworkResultOutput) ToLookupExternalNetworkResultOutputWithContext(ctx context.Context) LookupExternalNetworkResultOutput {
	return o
}

func (o LookupExternalNetworkResultOutput) Description() pulumi.StringOutput {
	return o.ApplyT(func(v LookupExternalNetworkResult) string { return v.Description }).(pulumi.StringOutput)
}

// The provider-assigned unique ID for this managed resource.
func (o LookupExternalNetworkResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v LookupExternalNetworkResult) string { return v.Id }).(pulumi.StringOutput)
}

func (o LookupExternalNetworkResultOutput) IpScopes() GetExternalNetworkIpScopeArrayOutput {
	return o.ApplyT(func(v LookupExternalNetworkResult) []GetExternalNetworkIpScope { return v.IpScopes }).(GetExternalNetworkIpScopeArrayOutput)
}

func (o LookupExternalNetworkResultOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v LookupExternalNetworkResult) string { return v.Name }).(pulumi.StringOutput)
}

func (o LookupExternalNetworkResultOutput) RetainNetInfoAcrossDeployments() pulumi.BoolOutput {
	return o.ApplyT(func(v LookupExternalNetworkResult) bool { return v.RetainNetInfoAcrossDeployments }).(pulumi.BoolOutput)
}

func (o LookupExternalNetworkResultOutput) VsphereNetworks() GetExternalNetworkVsphereNetworkArrayOutput {
	return o.ApplyT(func(v LookupExternalNetworkResult) []GetExternalNetworkVsphereNetwork { return v.VsphereNetworks }).(GetExternalNetworkVsphereNetworkArrayOutput)
}

func init() {
	pulumi.RegisterOutputType(LookupExternalNetworkResultOutput{})
}
