// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package vcd

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func LookupLbVirtualServer(ctx *pulumi.Context, args *LookupLbVirtualServerArgs, opts ...pulumi.InvokeOption) (*LookupLbVirtualServerResult, error) {
	var rv LookupLbVirtualServerResult
	err := ctx.Invoke("vcd:index/getLbVirtualServer:getLbVirtualServer", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getLbVirtualServer.
type LookupLbVirtualServerArgs struct {
	EdgeGateway string  `pulumi:"edgeGateway"`
	Name        string  `pulumi:"name"`
	Org         *string `pulumi:"org"`
	Vdc         *string `pulumi:"vdc"`
}

// A collection of values returned by getLbVirtualServer.
type LookupLbVirtualServerResult struct {
	AppProfileId        string   `pulumi:"appProfileId"`
	AppRuleIds          []string `pulumi:"appRuleIds"`
	ConnectionLimit     int      `pulumi:"connectionLimit"`
	ConnectionRateLimit int      `pulumi:"connectionRateLimit"`
	Description         string   `pulumi:"description"`
	EdgeGateway         string   `pulumi:"edgeGateway"`
	EnableAcceleration  bool     `pulumi:"enableAcceleration"`
	Enabled             bool     `pulumi:"enabled"`
	// The provider-assigned unique ID for this managed resource.
	Id           string  `pulumi:"id"`
	IpAddress    string  `pulumi:"ipAddress"`
	Name         string  `pulumi:"name"`
	Org          *string `pulumi:"org"`
	Port         int     `pulumi:"port"`
	Protocol     string  `pulumi:"protocol"`
	ServerPoolId string  `pulumi:"serverPoolId"`
	Vdc          *string `pulumi:"vdc"`
}

func LookupLbVirtualServerOutput(ctx *pulumi.Context, args LookupLbVirtualServerOutputArgs, opts ...pulumi.InvokeOption) LookupLbVirtualServerResultOutput {
	return pulumi.ToOutputWithContext(context.Background(), args).
		ApplyT(func(v interface{}) (LookupLbVirtualServerResult, error) {
			args := v.(LookupLbVirtualServerArgs)
			r, err := LookupLbVirtualServer(ctx, &args, opts...)
			var s LookupLbVirtualServerResult
			if r != nil {
				s = *r
			}
			return s, err
		}).(LookupLbVirtualServerResultOutput)
}

// A collection of arguments for invoking getLbVirtualServer.
type LookupLbVirtualServerOutputArgs struct {
	EdgeGateway pulumi.StringInput    `pulumi:"edgeGateway"`
	Name        pulumi.StringInput    `pulumi:"name"`
	Org         pulumi.StringPtrInput `pulumi:"org"`
	Vdc         pulumi.StringPtrInput `pulumi:"vdc"`
}

func (LookupLbVirtualServerOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupLbVirtualServerArgs)(nil)).Elem()
}

// A collection of values returned by getLbVirtualServer.
type LookupLbVirtualServerResultOutput struct{ *pulumi.OutputState }

func (LookupLbVirtualServerResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupLbVirtualServerResult)(nil)).Elem()
}

func (o LookupLbVirtualServerResultOutput) ToLookupLbVirtualServerResultOutput() LookupLbVirtualServerResultOutput {
	return o
}

func (o LookupLbVirtualServerResultOutput) ToLookupLbVirtualServerResultOutputWithContext(ctx context.Context) LookupLbVirtualServerResultOutput {
	return o
}

func (o LookupLbVirtualServerResultOutput) AppProfileId() pulumi.StringOutput {
	return o.ApplyT(func(v LookupLbVirtualServerResult) string { return v.AppProfileId }).(pulumi.StringOutput)
}

func (o LookupLbVirtualServerResultOutput) AppRuleIds() pulumi.StringArrayOutput {
	return o.ApplyT(func(v LookupLbVirtualServerResult) []string { return v.AppRuleIds }).(pulumi.StringArrayOutput)
}

func (o LookupLbVirtualServerResultOutput) ConnectionLimit() pulumi.IntOutput {
	return o.ApplyT(func(v LookupLbVirtualServerResult) int { return v.ConnectionLimit }).(pulumi.IntOutput)
}

func (o LookupLbVirtualServerResultOutput) ConnectionRateLimit() pulumi.IntOutput {
	return o.ApplyT(func(v LookupLbVirtualServerResult) int { return v.ConnectionRateLimit }).(pulumi.IntOutput)
}

func (o LookupLbVirtualServerResultOutput) Description() pulumi.StringOutput {
	return o.ApplyT(func(v LookupLbVirtualServerResult) string { return v.Description }).(pulumi.StringOutput)
}

func (o LookupLbVirtualServerResultOutput) EdgeGateway() pulumi.StringOutput {
	return o.ApplyT(func(v LookupLbVirtualServerResult) string { return v.EdgeGateway }).(pulumi.StringOutput)
}

func (o LookupLbVirtualServerResultOutput) EnableAcceleration() pulumi.BoolOutput {
	return o.ApplyT(func(v LookupLbVirtualServerResult) bool { return v.EnableAcceleration }).(pulumi.BoolOutput)
}

func (o LookupLbVirtualServerResultOutput) Enabled() pulumi.BoolOutput {
	return o.ApplyT(func(v LookupLbVirtualServerResult) bool { return v.Enabled }).(pulumi.BoolOutput)
}

// The provider-assigned unique ID for this managed resource.
func (o LookupLbVirtualServerResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v LookupLbVirtualServerResult) string { return v.Id }).(pulumi.StringOutput)
}

func (o LookupLbVirtualServerResultOutput) IpAddress() pulumi.StringOutput {
	return o.ApplyT(func(v LookupLbVirtualServerResult) string { return v.IpAddress }).(pulumi.StringOutput)
}

func (o LookupLbVirtualServerResultOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v LookupLbVirtualServerResult) string { return v.Name }).(pulumi.StringOutput)
}

func (o LookupLbVirtualServerResultOutput) Org() pulumi.StringPtrOutput {
	return o.ApplyT(func(v LookupLbVirtualServerResult) *string { return v.Org }).(pulumi.StringPtrOutput)
}

func (o LookupLbVirtualServerResultOutput) Port() pulumi.IntOutput {
	return o.ApplyT(func(v LookupLbVirtualServerResult) int { return v.Port }).(pulumi.IntOutput)
}

func (o LookupLbVirtualServerResultOutput) Protocol() pulumi.StringOutput {
	return o.ApplyT(func(v LookupLbVirtualServerResult) string { return v.Protocol }).(pulumi.StringOutput)
}

func (o LookupLbVirtualServerResultOutput) ServerPoolId() pulumi.StringOutput {
	return o.ApplyT(func(v LookupLbVirtualServerResult) string { return v.ServerPoolId }).(pulumi.StringOutput)
}

func (o LookupLbVirtualServerResultOutput) Vdc() pulumi.StringPtrOutput {
	return o.ApplyT(func(v LookupLbVirtualServerResult) *string { return v.Vdc }).(pulumi.StringPtrOutput)
}

func init() {
	pulumi.RegisterOutputType(LookupLbVirtualServerResultOutput{})
}
