// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package vcd

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func GetNsxtManager(ctx *pulumi.Context, args *GetNsxtManagerArgs, opts ...pulumi.InvokeOption) (*GetNsxtManagerResult, error) {
	var rv GetNsxtManagerResult
	err := ctx.Invoke("vcd:index/getNsxtManager:getNsxtManager", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getNsxtManager.
type GetNsxtManagerArgs struct {
	Name string `pulumi:"name"`
}

// A collection of values returned by getNsxtManager.
type GetNsxtManagerResult struct {
	// The provider-assigned unique ID for this managed resource.
	Id   string `pulumi:"id"`
	Name string `pulumi:"name"`
}

func GetNsxtManagerOutput(ctx *pulumi.Context, args GetNsxtManagerOutputArgs, opts ...pulumi.InvokeOption) GetNsxtManagerResultOutput {
	return pulumi.ToOutputWithContext(context.Background(), args).
		ApplyT(func(v interface{}) (GetNsxtManagerResult, error) {
			args := v.(GetNsxtManagerArgs)
			r, err := GetNsxtManager(ctx, &args, opts...)
			var s GetNsxtManagerResult
			if r != nil {
				s = *r
			}
			return s, err
		}).(GetNsxtManagerResultOutput)
}

// A collection of arguments for invoking getNsxtManager.
type GetNsxtManagerOutputArgs struct {
	Name pulumi.StringInput `pulumi:"name"`
}

func (GetNsxtManagerOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetNsxtManagerArgs)(nil)).Elem()
}

// A collection of values returned by getNsxtManager.
type GetNsxtManagerResultOutput struct{ *pulumi.OutputState }

func (GetNsxtManagerResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetNsxtManagerResult)(nil)).Elem()
}

func (o GetNsxtManagerResultOutput) ToGetNsxtManagerResultOutput() GetNsxtManagerResultOutput {
	return o
}

func (o GetNsxtManagerResultOutput) ToGetNsxtManagerResultOutputWithContext(ctx context.Context) GetNsxtManagerResultOutput {
	return o
}

// The provider-assigned unique ID for this managed resource.
func (o GetNsxtManagerResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v GetNsxtManagerResult) string { return v.Id }).(pulumi.StringOutput)
}

func (o GetNsxtManagerResultOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v GetNsxtManagerResult) string { return v.Name }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterOutputType(GetNsxtManagerResultOutput{})
}
