// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package vcd

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func LookupNsxtDynamicSecurityGroup(ctx *pulumi.Context, args *LookupNsxtDynamicSecurityGroupArgs, opts ...pulumi.InvokeOption) (*LookupNsxtDynamicSecurityGroupResult, error) {
	var rv LookupNsxtDynamicSecurityGroupResult
	err := ctx.Invoke("vcd:index/getNsxtDynamicSecurityGroup:getNsxtDynamicSecurityGroup", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getNsxtDynamicSecurityGroup.
type LookupNsxtDynamicSecurityGroupArgs struct {
	Description *string `pulumi:"description"`
	Name        string  `pulumi:"name"`
	Org         *string `pulumi:"org"`
	VdcGroupId  string  `pulumi:"vdcGroupId"`
}

// A collection of values returned by getNsxtDynamicSecurityGroup.
type LookupNsxtDynamicSecurityGroupResult struct {
	Criterias   []GetNsxtDynamicSecurityGroupCriteria `pulumi:"criterias"`
	Description *string                               `pulumi:"description"`
	// The provider-assigned unique ID for this managed resource.
	Id         string                                `pulumi:"id"`
	MemberVms  []GetNsxtDynamicSecurityGroupMemberVm `pulumi:"memberVms"`
	Name       string                                `pulumi:"name"`
	Org        *string                               `pulumi:"org"`
	VdcGroupId string                                `pulumi:"vdcGroupId"`
}

func LookupNsxtDynamicSecurityGroupOutput(ctx *pulumi.Context, args LookupNsxtDynamicSecurityGroupOutputArgs, opts ...pulumi.InvokeOption) LookupNsxtDynamicSecurityGroupResultOutput {
	return pulumi.ToOutputWithContext(context.Background(), args).
		ApplyT(func(v interface{}) (LookupNsxtDynamicSecurityGroupResult, error) {
			args := v.(LookupNsxtDynamicSecurityGroupArgs)
			r, err := LookupNsxtDynamicSecurityGroup(ctx, &args, opts...)
			var s LookupNsxtDynamicSecurityGroupResult
			if r != nil {
				s = *r
			}
			return s, err
		}).(LookupNsxtDynamicSecurityGroupResultOutput)
}

// A collection of arguments for invoking getNsxtDynamicSecurityGroup.
type LookupNsxtDynamicSecurityGroupOutputArgs struct {
	Description pulumi.StringPtrInput `pulumi:"description"`
	Name        pulumi.StringInput    `pulumi:"name"`
	Org         pulumi.StringPtrInput `pulumi:"org"`
	VdcGroupId  pulumi.StringInput    `pulumi:"vdcGroupId"`
}

func (LookupNsxtDynamicSecurityGroupOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupNsxtDynamicSecurityGroupArgs)(nil)).Elem()
}

// A collection of values returned by getNsxtDynamicSecurityGroup.
type LookupNsxtDynamicSecurityGroupResultOutput struct{ *pulumi.OutputState }

func (LookupNsxtDynamicSecurityGroupResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupNsxtDynamicSecurityGroupResult)(nil)).Elem()
}

func (o LookupNsxtDynamicSecurityGroupResultOutput) ToLookupNsxtDynamicSecurityGroupResultOutput() LookupNsxtDynamicSecurityGroupResultOutput {
	return o
}

func (o LookupNsxtDynamicSecurityGroupResultOutput) ToLookupNsxtDynamicSecurityGroupResultOutputWithContext(ctx context.Context) LookupNsxtDynamicSecurityGroupResultOutput {
	return o
}

func (o LookupNsxtDynamicSecurityGroupResultOutput) Criterias() GetNsxtDynamicSecurityGroupCriteriaArrayOutput {
	return o.ApplyT(func(v LookupNsxtDynamicSecurityGroupResult) []GetNsxtDynamicSecurityGroupCriteria { return v.Criterias }).(GetNsxtDynamicSecurityGroupCriteriaArrayOutput)
}

func (o LookupNsxtDynamicSecurityGroupResultOutput) Description() pulumi.StringPtrOutput {
	return o.ApplyT(func(v LookupNsxtDynamicSecurityGroupResult) *string { return v.Description }).(pulumi.StringPtrOutput)
}

// The provider-assigned unique ID for this managed resource.
func (o LookupNsxtDynamicSecurityGroupResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v LookupNsxtDynamicSecurityGroupResult) string { return v.Id }).(pulumi.StringOutput)
}

func (o LookupNsxtDynamicSecurityGroupResultOutput) MemberVms() GetNsxtDynamicSecurityGroupMemberVmArrayOutput {
	return o.ApplyT(func(v LookupNsxtDynamicSecurityGroupResult) []GetNsxtDynamicSecurityGroupMemberVm { return v.MemberVms }).(GetNsxtDynamicSecurityGroupMemberVmArrayOutput)
}

func (o LookupNsxtDynamicSecurityGroupResultOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v LookupNsxtDynamicSecurityGroupResult) string { return v.Name }).(pulumi.StringOutput)
}

func (o LookupNsxtDynamicSecurityGroupResultOutput) Org() pulumi.StringPtrOutput {
	return o.ApplyT(func(v LookupNsxtDynamicSecurityGroupResult) *string { return v.Org }).(pulumi.StringPtrOutput)
}

func (o LookupNsxtDynamicSecurityGroupResultOutput) VdcGroupId() pulumi.StringOutput {
	return o.ApplyT(func(v LookupNsxtDynamicSecurityGroupResult) string { return v.VdcGroupId }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterOutputType(LookupNsxtDynamicSecurityGroupResultOutput{})
}
