// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package vcd

import (
	"context"
	"reflect"

	"github.com/pkg/errors"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

type NsxtEdgegatewayBgpConfiguration struct {
	pulumi.CustomResourceState

	// Defines if ECMP (Equal-cost multi-path routing) is enabled
	EcmpEnabled pulumi.BoolPtrOutput `pulumi:"ecmpEnabled"`
	// Edge gateway ID for BGP Configuration
	EdgeGatewayId pulumi.StringOutput `pulumi:"edgeGatewayId"`
	// Defines if BGP service is enabled
	Enabled pulumi.BoolOutput `pulumi:"enabled"`
	// Graceful restart configuration on Edge Gateway. One of 'DISABLE', 'HELPER_ONLY', 'GRACEFUL_AND_HELPER'
	GracefulRestartMode pulumi.StringOutput `pulumi:"gracefulRestartMode"`
	// Maximum time taken (in seconds) for a BGP session to be established after a restart
	GracefulRestartTimer pulumi.IntOutput `pulumi:"gracefulRestartTimer"`
	// Autonomous system number
	LocalAsNumber pulumi.StringOutput `pulumi:"localAsNumber"`
	// The name of organization to use, optional if defined at provider level. Useful when connected as sysadmin working across
	// different organizations
	Org pulumi.StringPtrOutput `pulumi:"org"`
	// Maximum time (in seconds) before stale routes are removed when BGP restarts
	StaleRouteTimer pulumi.IntOutput `pulumi:"staleRouteTimer"`
}

// NewNsxtEdgegatewayBgpConfiguration registers a new resource with the given unique name, arguments, and options.
func NewNsxtEdgegatewayBgpConfiguration(ctx *pulumi.Context,
	name string, args *NsxtEdgegatewayBgpConfigurationArgs, opts ...pulumi.ResourceOption) (*NsxtEdgegatewayBgpConfiguration, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.EdgeGatewayId == nil {
		return nil, errors.New("invalid value for required argument 'EdgeGatewayId'")
	}
	if args.Enabled == nil {
		return nil, errors.New("invalid value for required argument 'Enabled'")
	}
	var resource NsxtEdgegatewayBgpConfiguration
	err := ctx.RegisterResource("vcd:index/nsxtEdgegatewayBgpConfiguration:NsxtEdgegatewayBgpConfiguration", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetNsxtEdgegatewayBgpConfiguration gets an existing NsxtEdgegatewayBgpConfiguration resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetNsxtEdgegatewayBgpConfiguration(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *NsxtEdgegatewayBgpConfigurationState, opts ...pulumi.ResourceOption) (*NsxtEdgegatewayBgpConfiguration, error) {
	var resource NsxtEdgegatewayBgpConfiguration
	err := ctx.ReadResource("vcd:index/nsxtEdgegatewayBgpConfiguration:NsxtEdgegatewayBgpConfiguration", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering NsxtEdgegatewayBgpConfiguration resources.
type nsxtEdgegatewayBgpConfigurationState struct {
	// Defines if ECMP (Equal-cost multi-path routing) is enabled
	EcmpEnabled *bool `pulumi:"ecmpEnabled"`
	// Edge gateway ID for BGP Configuration
	EdgeGatewayId *string `pulumi:"edgeGatewayId"`
	// Defines if BGP service is enabled
	Enabled *bool `pulumi:"enabled"`
	// Graceful restart configuration on Edge Gateway. One of 'DISABLE', 'HELPER_ONLY', 'GRACEFUL_AND_HELPER'
	GracefulRestartMode *string `pulumi:"gracefulRestartMode"`
	// Maximum time taken (in seconds) for a BGP session to be established after a restart
	GracefulRestartTimer *int `pulumi:"gracefulRestartTimer"`
	// Autonomous system number
	LocalAsNumber *string `pulumi:"localAsNumber"`
	// The name of organization to use, optional if defined at provider level. Useful when connected as sysadmin working across
	// different organizations
	Org *string `pulumi:"org"`
	// Maximum time (in seconds) before stale routes are removed when BGP restarts
	StaleRouteTimer *int `pulumi:"staleRouteTimer"`
}

type NsxtEdgegatewayBgpConfigurationState struct {
	// Defines if ECMP (Equal-cost multi-path routing) is enabled
	EcmpEnabled pulumi.BoolPtrInput
	// Edge gateway ID for BGP Configuration
	EdgeGatewayId pulumi.StringPtrInput
	// Defines if BGP service is enabled
	Enabled pulumi.BoolPtrInput
	// Graceful restart configuration on Edge Gateway. One of 'DISABLE', 'HELPER_ONLY', 'GRACEFUL_AND_HELPER'
	GracefulRestartMode pulumi.StringPtrInput
	// Maximum time taken (in seconds) for a BGP session to be established after a restart
	GracefulRestartTimer pulumi.IntPtrInput
	// Autonomous system number
	LocalAsNumber pulumi.StringPtrInput
	// The name of organization to use, optional if defined at provider level. Useful when connected as sysadmin working across
	// different organizations
	Org pulumi.StringPtrInput
	// Maximum time (in seconds) before stale routes are removed when BGP restarts
	StaleRouteTimer pulumi.IntPtrInput
}

func (NsxtEdgegatewayBgpConfigurationState) ElementType() reflect.Type {
	return reflect.TypeOf((*nsxtEdgegatewayBgpConfigurationState)(nil)).Elem()
}

type nsxtEdgegatewayBgpConfigurationArgs struct {
	// Defines if ECMP (Equal-cost multi-path routing) is enabled
	EcmpEnabled *bool `pulumi:"ecmpEnabled"`
	// Edge gateway ID for BGP Configuration
	EdgeGatewayId string `pulumi:"edgeGatewayId"`
	// Defines if BGP service is enabled
	Enabled bool `pulumi:"enabled"`
	// Graceful restart configuration on Edge Gateway. One of 'DISABLE', 'HELPER_ONLY', 'GRACEFUL_AND_HELPER'
	GracefulRestartMode *string `pulumi:"gracefulRestartMode"`
	// Maximum time taken (in seconds) for a BGP session to be established after a restart
	GracefulRestartTimer *int `pulumi:"gracefulRestartTimer"`
	// Autonomous system number
	LocalAsNumber *string `pulumi:"localAsNumber"`
	// The name of organization to use, optional if defined at provider level. Useful when connected as sysadmin working across
	// different organizations
	Org *string `pulumi:"org"`
	// Maximum time (in seconds) before stale routes are removed when BGP restarts
	StaleRouteTimer *int `pulumi:"staleRouteTimer"`
}

// The set of arguments for constructing a NsxtEdgegatewayBgpConfiguration resource.
type NsxtEdgegatewayBgpConfigurationArgs struct {
	// Defines if ECMP (Equal-cost multi-path routing) is enabled
	EcmpEnabled pulumi.BoolPtrInput
	// Edge gateway ID for BGP Configuration
	EdgeGatewayId pulumi.StringInput
	// Defines if BGP service is enabled
	Enabled pulumi.BoolInput
	// Graceful restart configuration on Edge Gateway. One of 'DISABLE', 'HELPER_ONLY', 'GRACEFUL_AND_HELPER'
	GracefulRestartMode pulumi.StringPtrInput
	// Maximum time taken (in seconds) for a BGP session to be established after a restart
	GracefulRestartTimer pulumi.IntPtrInput
	// Autonomous system number
	LocalAsNumber pulumi.StringPtrInput
	// The name of organization to use, optional if defined at provider level. Useful when connected as sysadmin working across
	// different organizations
	Org pulumi.StringPtrInput
	// Maximum time (in seconds) before stale routes are removed when BGP restarts
	StaleRouteTimer pulumi.IntPtrInput
}

func (NsxtEdgegatewayBgpConfigurationArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*nsxtEdgegatewayBgpConfigurationArgs)(nil)).Elem()
}

type NsxtEdgegatewayBgpConfigurationInput interface {
	pulumi.Input

	ToNsxtEdgegatewayBgpConfigurationOutput() NsxtEdgegatewayBgpConfigurationOutput
	ToNsxtEdgegatewayBgpConfigurationOutputWithContext(ctx context.Context) NsxtEdgegatewayBgpConfigurationOutput
}

func (*NsxtEdgegatewayBgpConfiguration) ElementType() reflect.Type {
	return reflect.TypeOf((**NsxtEdgegatewayBgpConfiguration)(nil)).Elem()
}

func (i *NsxtEdgegatewayBgpConfiguration) ToNsxtEdgegatewayBgpConfigurationOutput() NsxtEdgegatewayBgpConfigurationOutput {
	return i.ToNsxtEdgegatewayBgpConfigurationOutputWithContext(context.Background())
}

func (i *NsxtEdgegatewayBgpConfiguration) ToNsxtEdgegatewayBgpConfigurationOutputWithContext(ctx context.Context) NsxtEdgegatewayBgpConfigurationOutput {
	return pulumi.ToOutputWithContext(ctx, i).(NsxtEdgegatewayBgpConfigurationOutput)
}

// NsxtEdgegatewayBgpConfigurationArrayInput is an input type that accepts NsxtEdgegatewayBgpConfigurationArray and NsxtEdgegatewayBgpConfigurationArrayOutput values.
// You can construct a concrete instance of `NsxtEdgegatewayBgpConfigurationArrayInput` via:
//
//	NsxtEdgegatewayBgpConfigurationArray{ NsxtEdgegatewayBgpConfigurationArgs{...} }
type NsxtEdgegatewayBgpConfigurationArrayInput interface {
	pulumi.Input

	ToNsxtEdgegatewayBgpConfigurationArrayOutput() NsxtEdgegatewayBgpConfigurationArrayOutput
	ToNsxtEdgegatewayBgpConfigurationArrayOutputWithContext(context.Context) NsxtEdgegatewayBgpConfigurationArrayOutput
}

type NsxtEdgegatewayBgpConfigurationArray []NsxtEdgegatewayBgpConfigurationInput

func (NsxtEdgegatewayBgpConfigurationArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*NsxtEdgegatewayBgpConfiguration)(nil)).Elem()
}

func (i NsxtEdgegatewayBgpConfigurationArray) ToNsxtEdgegatewayBgpConfigurationArrayOutput() NsxtEdgegatewayBgpConfigurationArrayOutput {
	return i.ToNsxtEdgegatewayBgpConfigurationArrayOutputWithContext(context.Background())
}

func (i NsxtEdgegatewayBgpConfigurationArray) ToNsxtEdgegatewayBgpConfigurationArrayOutputWithContext(ctx context.Context) NsxtEdgegatewayBgpConfigurationArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(NsxtEdgegatewayBgpConfigurationArrayOutput)
}

// NsxtEdgegatewayBgpConfigurationMapInput is an input type that accepts NsxtEdgegatewayBgpConfigurationMap and NsxtEdgegatewayBgpConfigurationMapOutput values.
// You can construct a concrete instance of `NsxtEdgegatewayBgpConfigurationMapInput` via:
//
//	NsxtEdgegatewayBgpConfigurationMap{ "key": NsxtEdgegatewayBgpConfigurationArgs{...} }
type NsxtEdgegatewayBgpConfigurationMapInput interface {
	pulumi.Input

	ToNsxtEdgegatewayBgpConfigurationMapOutput() NsxtEdgegatewayBgpConfigurationMapOutput
	ToNsxtEdgegatewayBgpConfigurationMapOutputWithContext(context.Context) NsxtEdgegatewayBgpConfigurationMapOutput
}

type NsxtEdgegatewayBgpConfigurationMap map[string]NsxtEdgegatewayBgpConfigurationInput

func (NsxtEdgegatewayBgpConfigurationMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*NsxtEdgegatewayBgpConfiguration)(nil)).Elem()
}

func (i NsxtEdgegatewayBgpConfigurationMap) ToNsxtEdgegatewayBgpConfigurationMapOutput() NsxtEdgegatewayBgpConfigurationMapOutput {
	return i.ToNsxtEdgegatewayBgpConfigurationMapOutputWithContext(context.Background())
}

func (i NsxtEdgegatewayBgpConfigurationMap) ToNsxtEdgegatewayBgpConfigurationMapOutputWithContext(ctx context.Context) NsxtEdgegatewayBgpConfigurationMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(NsxtEdgegatewayBgpConfigurationMapOutput)
}

type NsxtEdgegatewayBgpConfigurationOutput struct{ *pulumi.OutputState }

func (NsxtEdgegatewayBgpConfigurationOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**NsxtEdgegatewayBgpConfiguration)(nil)).Elem()
}

func (o NsxtEdgegatewayBgpConfigurationOutput) ToNsxtEdgegatewayBgpConfigurationOutput() NsxtEdgegatewayBgpConfigurationOutput {
	return o
}

func (o NsxtEdgegatewayBgpConfigurationOutput) ToNsxtEdgegatewayBgpConfigurationOutputWithContext(ctx context.Context) NsxtEdgegatewayBgpConfigurationOutput {
	return o
}

// Defines if ECMP (Equal-cost multi-path routing) is enabled
func (o NsxtEdgegatewayBgpConfigurationOutput) EcmpEnabled() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v *NsxtEdgegatewayBgpConfiguration) pulumi.BoolPtrOutput { return v.EcmpEnabled }).(pulumi.BoolPtrOutput)
}

// Edge gateway ID for BGP Configuration
func (o NsxtEdgegatewayBgpConfigurationOutput) EdgeGatewayId() pulumi.StringOutput {
	return o.ApplyT(func(v *NsxtEdgegatewayBgpConfiguration) pulumi.StringOutput { return v.EdgeGatewayId }).(pulumi.StringOutput)
}

// Defines if BGP service is enabled
func (o NsxtEdgegatewayBgpConfigurationOutput) Enabled() pulumi.BoolOutput {
	return o.ApplyT(func(v *NsxtEdgegatewayBgpConfiguration) pulumi.BoolOutput { return v.Enabled }).(pulumi.BoolOutput)
}

// Graceful restart configuration on Edge Gateway. One of 'DISABLE', 'HELPER_ONLY', 'GRACEFUL_AND_HELPER'
func (o NsxtEdgegatewayBgpConfigurationOutput) GracefulRestartMode() pulumi.StringOutput {
	return o.ApplyT(func(v *NsxtEdgegatewayBgpConfiguration) pulumi.StringOutput { return v.GracefulRestartMode }).(pulumi.StringOutput)
}

// Maximum time taken (in seconds) for a BGP session to be established after a restart
func (o NsxtEdgegatewayBgpConfigurationOutput) GracefulRestartTimer() pulumi.IntOutput {
	return o.ApplyT(func(v *NsxtEdgegatewayBgpConfiguration) pulumi.IntOutput { return v.GracefulRestartTimer }).(pulumi.IntOutput)
}

// Autonomous system number
func (o NsxtEdgegatewayBgpConfigurationOutput) LocalAsNumber() pulumi.StringOutput {
	return o.ApplyT(func(v *NsxtEdgegatewayBgpConfiguration) pulumi.StringOutput { return v.LocalAsNumber }).(pulumi.StringOutput)
}

// The name of organization to use, optional if defined at provider level. Useful when connected as sysadmin working across
// different organizations
func (o NsxtEdgegatewayBgpConfigurationOutput) Org() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *NsxtEdgegatewayBgpConfiguration) pulumi.StringPtrOutput { return v.Org }).(pulumi.StringPtrOutput)
}

// Maximum time (in seconds) before stale routes are removed when BGP restarts
func (o NsxtEdgegatewayBgpConfigurationOutput) StaleRouteTimer() pulumi.IntOutput {
	return o.ApplyT(func(v *NsxtEdgegatewayBgpConfiguration) pulumi.IntOutput { return v.StaleRouteTimer }).(pulumi.IntOutput)
}

type NsxtEdgegatewayBgpConfigurationArrayOutput struct{ *pulumi.OutputState }

func (NsxtEdgegatewayBgpConfigurationArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*NsxtEdgegatewayBgpConfiguration)(nil)).Elem()
}

func (o NsxtEdgegatewayBgpConfigurationArrayOutput) ToNsxtEdgegatewayBgpConfigurationArrayOutput() NsxtEdgegatewayBgpConfigurationArrayOutput {
	return o
}

func (o NsxtEdgegatewayBgpConfigurationArrayOutput) ToNsxtEdgegatewayBgpConfigurationArrayOutputWithContext(ctx context.Context) NsxtEdgegatewayBgpConfigurationArrayOutput {
	return o
}

func (o NsxtEdgegatewayBgpConfigurationArrayOutput) Index(i pulumi.IntInput) NsxtEdgegatewayBgpConfigurationOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *NsxtEdgegatewayBgpConfiguration {
		return vs[0].([]*NsxtEdgegatewayBgpConfiguration)[vs[1].(int)]
	}).(NsxtEdgegatewayBgpConfigurationOutput)
}

type NsxtEdgegatewayBgpConfigurationMapOutput struct{ *pulumi.OutputState }

func (NsxtEdgegatewayBgpConfigurationMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*NsxtEdgegatewayBgpConfiguration)(nil)).Elem()
}

func (o NsxtEdgegatewayBgpConfigurationMapOutput) ToNsxtEdgegatewayBgpConfigurationMapOutput() NsxtEdgegatewayBgpConfigurationMapOutput {
	return o
}

func (o NsxtEdgegatewayBgpConfigurationMapOutput) ToNsxtEdgegatewayBgpConfigurationMapOutputWithContext(ctx context.Context) NsxtEdgegatewayBgpConfigurationMapOutput {
	return o
}

func (o NsxtEdgegatewayBgpConfigurationMapOutput) MapIndex(k pulumi.StringInput) NsxtEdgegatewayBgpConfigurationOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *NsxtEdgegatewayBgpConfiguration {
		return vs[0].(map[string]*NsxtEdgegatewayBgpConfiguration)[vs[1].(string)]
	}).(NsxtEdgegatewayBgpConfigurationOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*NsxtEdgegatewayBgpConfigurationInput)(nil)).Elem(), &NsxtEdgegatewayBgpConfiguration{})
	pulumi.RegisterInputType(reflect.TypeOf((*NsxtEdgegatewayBgpConfigurationArrayInput)(nil)).Elem(), NsxtEdgegatewayBgpConfigurationArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*NsxtEdgegatewayBgpConfigurationMapInput)(nil)).Elem(), NsxtEdgegatewayBgpConfigurationMap{})
	pulumi.RegisterOutputType(NsxtEdgegatewayBgpConfigurationOutput{})
	pulumi.RegisterOutputType(NsxtEdgegatewayBgpConfigurationArrayOutput{})
	pulumi.RegisterOutputType(NsxtEdgegatewayBgpConfigurationMapOutput{})
}
