// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Vcd.Inputs
{

    public sealed class GetSubscribedCatalogFilterArgs : global::Pulumi.InvokeArgs
    {
        [Input("date")]
        public string? Date { get; set; }

        [Input("earliest")]
        public bool? Earliest { get; set; }

        [Input("latest")]
        public bool? Latest { get; set; }

        [Input("metadatas")]
        private List<Inputs.GetSubscribedCatalogFilterMetadataArgs>? _metadatas;
        public List<Inputs.GetSubscribedCatalogFilterMetadataArgs> Metadatas
        {
            get => _metadatas ?? (_metadatas = new List<Inputs.GetSubscribedCatalogFilterMetadataArgs>());
            set => _metadatas = value;
        }

        [Input("nameRegex")]
        public string? NameRegex { get; set; }

        public GetSubscribedCatalogFilterArgs()
        {
        }
        public static new GetSubscribedCatalogFilterArgs Empty => new GetSubscribedCatalogFilterArgs();
    }
}
