// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Vcd.Inputs
{

    public sealed class NsxtEdgegatewayBgpIpPrefixListIpPrefixGetArgs : global::Pulumi.ResourceArgs
    {
        [Input("action", required: true)]
        public Input<string> Action { get; set; } = null!;

        [Input("greaterThanOrEqualTo")]
        public Input<int>? GreaterThanOrEqualTo { get; set; }

        [Input("lessThanOrEqualTo")]
        public Input<int>? LessThanOrEqualTo { get; set; }

        [Input("network", required: true)]
        public Input<string> Network { get; set; } = null!;

        public NsxtEdgegatewayBgpIpPrefixListIpPrefixGetArgs()
        {
        }
        public static new NsxtEdgegatewayBgpIpPrefixListIpPrefixGetArgs Empty => new NsxtEdgegatewayBgpIpPrefixListIpPrefixGetArgs();
    }
}
