// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import { input as inputs, output as outputs } from "./types";
import * as utilities from "./utilities";

export function getCatalogVappTemplate(args?: GetCatalogVappTemplateArgs, opts?: pulumi.InvokeOptions): Promise<GetCatalogVappTemplateResult> {
    args = args || {};
    if (!opts) {
        opts = {}
    }

    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
    return pulumi.runtime.invoke("vcd:index/getCatalogVappTemplate:getCatalogVappTemplate", {
        "catalogId": args.catalogId,
        "filter": args.filter,
        "name": args.name,
        "org": args.org,
        "vdcId": args.vdcId,
    }, opts);
}

/**
 * A collection of arguments for invoking getCatalogVappTemplate.
 */
export interface GetCatalogVappTemplateArgs {
    catalogId?: string;
    filter?: inputs.GetCatalogVappTemplateFilter;
    name?: string;
    org?: string;
    vdcId?: string;
}

/**
 * A collection of values returned by getCatalogVappTemplate.
 */
export interface GetCatalogVappTemplateResult {
    readonly catalogId?: string;
    readonly created: string;
    readonly description: string;
    readonly filter?: outputs.GetCatalogVappTemplateFilter;
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    /**
     * @deprecated Use metadata_entry instead
     */
    readonly metadata: {[key: string]: any};
    readonly metadataEntries: outputs.GetCatalogVappTemplateMetadataEntry[];
    readonly name?: string;
    readonly org?: string;
    readonly vdcId?: string;
    readonly vmNames: string[];
}

export function getCatalogVappTemplateOutput(args?: GetCatalogVappTemplateOutputArgs, opts?: pulumi.InvokeOptions): pulumi.Output<GetCatalogVappTemplateResult> {
    return pulumi.output(args).apply(a => getCatalogVappTemplate(a, opts))
}

/**
 * A collection of arguments for invoking getCatalogVappTemplate.
 */
export interface GetCatalogVappTemplateOutputArgs {
    catalogId?: pulumi.Input<string>;
    filter?: pulumi.Input<inputs.GetCatalogVappTemplateFilterArgs>;
    name?: pulumi.Input<string>;
    org?: pulumi.Input<string>;
    vdcId?: pulumi.Input<string>;
}
