// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import { input as inputs, output as outputs } from "./types";
import * as utilities from "./utilities";

export function getIndependentDisk(args?: GetIndependentDiskArgs, opts?: pulumi.InvokeOptions): Promise<GetIndependentDiskResult> {
    args = args || {};
    if (!opts) {
        opts = {}
    }

    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
    return pulumi.runtime.invoke("vcd:index/getIndependentDisk:getIndependentDisk", {
        "id": args.id,
        "name": args.name,
        "org": args.org,
        "vdc": args.vdc,
    }, opts);
}

/**
 * A collection of arguments for invoking getIndependentDisk.
 */
export interface GetIndependentDiskArgs {
    id?: string;
    name?: string;
    org?: string;
    vdc?: string;
}

/**
 * A collection of values returned by getIndependentDisk.
 */
export interface GetIndependentDiskResult {
    readonly attachedVmIds: string[];
    readonly busSubType: string;
    readonly busType: string;
    readonly datastoreName: string;
    readonly description: string;
    readonly encrypted: boolean;
    readonly id?: string;
    readonly iops: number;
    readonly isAttached: boolean;
    /**
     * @deprecated Use metadata_entry instead
     */
    readonly metadata: {[key: string]: any};
    readonly metadataEntries: outputs.GetIndependentDiskMetadataEntry[];
    readonly name?: string;
    readonly org?: string;
    readonly ownerName: string;
    readonly sharingType: string;
    readonly sizeInMb: number;
    readonly storageProfile: string;
    readonly uuid: string;
    readonly vdc?: string;
}

export function getIndependentDiskOutput(args?: GetIndependentDiskOutputArgs, opts?: pulumi.InvokeOptions): pulumi.Output<GetIndependentDiskResult> {
    return pulumi.output(args).apply(a => getIndependentDisk(a, opts))
}

/**
 * A collection of arguments for invoking getIndependentDisk.
 */
export interface GetIndependentDiskOutputArgs {
    id?: pulumi.Input<string>;
    name?: pulumi.Input<string>;
    org?: pulumi.Input<string>;
    vdc?: pulumi.Input<string>;
}
