// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import { input as inputs, output as outputs } from "./types";
import * as utilities from "./utilities";

export function getNetworkIsolated(args?: GetNetworkIsolatedArgs, opts?: pulumi.InvokeOptions): Promise<GetNetworkIsolatedResult> {
    args = args || {};
    if (!opts) {
        opts = {}
    }

    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
    return pulumi.runtime.invoke("vcd:index/getNetworkIsolated:getNetworkIsolated", {
        "filter": args.filter,
        "name": args.name,
        "org": args.org,
        "vdc": args.vdc,
    }, opts);
}

/**
 * A collection of arguments for invoking getNetworkIsolated.
 */
export interface GetNetworkIsolatedArgs {
    filter?: inputs.GetNetworkIsolatedFilter;
    name?: string;
    org?: string;
    vdc?: string;
}

/**
 * A collection of values returned by getNetworkIsolated.
 */
export interface GetNetworkIsolatedResult {
    readonly description: string;
    readonly dhcpPools: outputs.GetNetworkIsolatedDhcpPool[];
    readonly dns1: string;
    readonly dns2: string;
    readonly dnsSuffix: string;
    readonly filter?: outputs.GetNetworkIsolatedFilter;
    readonly gateway: string;
    readonly href: string;
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    /**
     * @deprecated Use metadata_entry instead
     */
    readonly metadata: {[key: string]: any};
    readonly metadataEntries: outputs.GetNetworkIsolatedMetadataEntry[];
    readonly name?: string;
    readonly netmask: string;
    readonly org?: string;
    readonly shared: boolean;
    readonly staticIpPools: outputs.GetNetworkIsolatedStaticIpPool[];
    readonly vdc?: string;
}

export function getNetworkIsolatedOutput(args?: GetNetworkIsolatedOutputArgs, opts?: pulumi.InvokeOptions): pulumi.Output<GetNetworkIsolatedResult> {
    return pulumi.output(args).apply(a => getNetworkIsolated(a, opts))
}

/**
 * A collection of arguments for invoking getNetworkIsolated.
 */
export interface GetNetworkIsolatedOutputArgs {
    filter?: pulumi.Input<inputs.GetNetworkIsolatedFilterArgs>;
    name?: pulumi.Input<string>;
    org?: pulumi.Input<string>;
    vdc?: pulumi.Input<string>;
}
