// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export function getNsxtEdgeCluster(args: GetNsxtEdgeClusterArgs, opts?: pulumi.InvokeOptions): Promise<GetNsxtEdgeClusterResult> {
    if (!opts) {
        opts = {}
    }

    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
    return pulumi.runtime.invoke("vcd:index/getNsxtEdgeCluster:getNsxtEdgeCluster", {
        "name": args.name,
        "org": args.org,
        "providerVdcId": args.providerVdcId,
        "vdc": args.vdc,
        "vdcGroupId": args.vdcGroupId,
        "vdcId": args.vdcId,
    }, opts);
}

/**
 * A collection of arguments for invoking getNsxtEdgeCluster.
 */
export interface GetNsxtEdgeClusterArgs {
    name: string;
    org?: string;
    providerVdcId?: string;
    /**
     * @deprecated This field is deprecated in favor of 'vdc_id', 'vdc_group_id', and 'provider_vdc_id' which accept IDs of VDC, VDC Group and Provider VDC respectively
     */
    vdc?: string;
    vdcGroupId?: string;
    vdcId?: string;
}

/**
 * A collection of values returned by getNsxtEdgeCluster.
 */
export interface GetNsxtEdgeClusterResult {
    readonly deploymentType: string;
    readonly description: string;
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    readonly name: string;
    readonly nodeCount: number;
    readonly nodeType: string;
    readonly org?: string;
    readonly providerVdcId?: string;
    /**
     * @deprecated This field is deprecated in favor of 'vdc_id', 'vdc_group_id', and 'provider_vdc_id' which accept IDs of VDC, VDC Group and Provider VDC respectively
     */
    readonly vdc?: string;
    readonly vdcGroupId?: string;
    readonly vdcId?: string;
}

export function getNsxtEdgeClusterOutput(args: GetNsxtEdgeClusterOutputArgs, opts?: pulumi.InvokeOptions): pulumi.Output<GetNsxtEdgeClusterResult> {
    return pulumi.output(args).apply(a => getNsxtEdgeCluster(a, opts))
}

/**
 * A collection of arguments for invoking getNsxtEdgeCluster.
 */
export interface GetNsxtEdgeClusterOutputArgs {
    name: pulumi.Input<string>;
    org?: pulumi.Input<string>;
    providerVdcId?: pulumi.Input<string>;
    /**
     * @deprecated This field is deprecated in favor of 'vdc_id', 'vdc_group_id', and 'provider_vdc_id' which accept IDs of VDC, VDC Group and Provider VDC respectively
     */
    vdc?: pulumi.Input<string>;
    vdcGroupId?: pulumi.Input<string>;
    vdcId?: pulumi.Input<string>;
}
