// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import { input as inputs, output as outputs } from "./types";
import * as utilities from "./utilities";

export function getNsxtAlbVirtualService(args: GetNsxtAlbVirtualServiceArgs, opts?: pulumi.InvokeOptions): Promise<GetNsxtAlbVirtualServiceResult> {
    if (!opts) {
        opts = {}
    }

    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
    return pulumi.runtime.invoke("vcd:index/getNsxtAlbVirtualService:getNsxtAlbVirtualService", {
        "edgeGatewayId": args.edgeGatewayId,
        "name": args.name,
        "org": args.org,
        "vdc": args.vdc,
    }, opts);
}

/**
 * A collection of arguments for invoking getNsxtAlbVirtualService.
 */
export interface GetNsxtAlbVirtualServiceArgs {
    edgeGatewayId: string;
    name: string;
    org?: string;
    /**
     * @deprecated Edge Gateway will be looked up based on 'edge_gateway_id' field
     */
    vdc?: string;
}

/**
 * A collection of values returned by getNsxtAlbVirtualService.
 */
export interface GetNsxtAlbVirtualServiceResult {
    readonly applicationProfileType: string;
    readonly caCertificateId: string;
    readonly description: string;
    readonly edgeGatewayId: string;
    readonly enabled: boolean;
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    readonly name: string;
    readonly org?: string;
    readonly poolId: string;
    readonly serviceEngineGroupId: string;
    readonly servicePorts: outputs.GetNsxtAlbVirtualServiceServicePort[];
    /**
     * @deprecated Edge Gateway will be looked up based on 'edge_gateway_id' field
     */
    readonly vdc: string;
    readonly virtualIpAddress: string;
}

export function getNsxtAlbVirtualServiceOutput(args: GetNsxtAlbVirtualServiceOutputArgs, opts?: pulumi.InvokeOptions): pulumi.Output<GetNsxtAlbVirtualServiceResult> {
    return pulumi.output(args).apply(a => getNsxtAlbVirtualService(a, opts))
}

/**
 * A collection of arguments for invoking getNsxtAlbVirtualService.
 */
export interface GetNsxtAlbVirtualServiceOutputArgs {
    edgeGatewayId: pulumi.Input<string>;
    name: pulumi.Input<string>;
    org?: pulumi.Input<string>;
    /**
     * @deprecated Edge Gateway will be looked up based on 'edge_gateway_id' field
     */
    vdc?: pulumi.Input<string>;
}
