// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import { input as inputs, output as outputs } from "./types";
import * as utilities from "./utilities";

export function getNetworkRoutedV2(args?: GetNetworkRoutedV2Args, opts?: pulumi.InvokeOptions): Promise<GetNetworkRoutedV2Result> {
    args = args || {};
    if (!opts) {
        opts = {}
    }

    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
    return pulumi.runtime.invoke("vcd:index/getNetworkRoutedV2:getNetworkRoutedV2", {
        "edgeGatewayId": args.edgeGatewayId,
        "filter": args.filter,
        "name": args.name,
        "org": args.org,
        "vdc": args.vdc,
    }, opts);
}

/**
 * A collection of arguments for invoking getNetworkRoutedV2.
 */
export interface GetNetworkRoutedV2Args {
    edgeGatewayId?: string;
    filter?: inputs.GetNetworkRoutedV2Filter;
    name?: string;
    org?: string;
    /**
     * @deprecated Deprecated in favor of `edge_gateway_id`. Routed networks will inherit VDC from parent Edge Gateway.
     */
    vdc?: string;
}

/**
 * A collection of values returned by getNetworkRoutedV2.
 */
export interface GetNetworkRoutedV2Result {
    readonly description: string;
    readonly dns1: string;
    readonly dns2: string;
    readonly dnsSuffix: string;
    readonly edgeGatewayId: string;
    readonly filter?: outputs.GetNetworkRoutedV2Filter;
    readonly gateway: string;
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    readonly interfaceType: string;
    /**
     * @deprecated Use metadata_entry instead
     */
    readonly metadata: {[key: string]: any};
    readonly metadataEntries: outputs.GetNetworkRoutedV2MetadataEntry[];
    readonly name?: string;
    readonly org?: string;
    readonly ownerId: string;
    readonly prefixLength: number;
    readonly staticIpPools: outputs.GetNetworkRoutedV2StaticIpPool[];
    /**
     * @deprecated Deprecated in favor of `edge_gateway_id`. Routed networks will inherit VDC from parent Edge Gateway.
     */
    readonly vdc?: string;
}

export function getNetworkRoutedV2Output(args?: GetNetworkRoutedV2OutputArgs, opts?: pulumi.InvokeOptions): pulumi.Output<GetNetworkRoutedV2Result> {
    return pulumi.output(args).apply(a => getNetworkRoutedV2(a, opts))
}

/**
 * A collection of arguments for invoking getNetworkRoutedV2.
 */
export interface GetNetworkRoutedV2OutputArgs {
    edgeGatewayId?: pulumi.Input<string>;
    filter?: pulumi.Input<inputs.GetNetworkRoutedV2FilterArgs>;
    name?: pulumi.Input<string>;
    org?: pulumi.Input<string>;
    /**
     * @deprecated Deprecated in favor of `edge_gateway_id`. Routed networks will inherit VDC from parent Edge Gateway.
     */
    vdc?: pulumi.Input<string>;
}
