// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export function getResourceList(args: GetResourceListArgs, opts?: pulumi.InvokeOptions): Promise<GetResourceListResult> {
    if (!opts) {
        opts = {}
    }

    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
    return pulumi.runtime.invoke("vcd:index/getResourceList:getResourceList", {
        "listMode": args.listMode,
        "name": args.name,
        "nameIdSeparator": args.nameIdSeparator,
        "org": args.org,
        "parent": args.parent,
        "resourceType": args.resourceType,
        "vdc": args.vdc,
    }, opts);
}

/**
 * A collection of arguments for invoking getResourceList.
 */
export interface GetResourceListArgs {
    listMode?: string;
    name: string;
    nameIdSeparator?: string;
    org?: string;
    parent?: string;
    resourceType: string;
    vdc?: string;
}

/**
 * A collection of values returned by getResourceList.
 */
export interface GetResourceListResult {
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    readonly listMode?: string;
    readonly lists: string[];
    readonly name: string;
    readonly nameIdSeparator?: string;
    readonly org?: string;
    readonly parent?: string;
    readonly resourceType: string;
    readonly vdc?: string;
}

export function getResourceListOutput(args: GetResourceListOutputArgs, opts?: pulumi.InvokeOptions): pulumi.Output<GetResourceListResult> {
    return pulumi.output(args).apply(a => getResourceList(a, opts))
}

/**
 * A collection of arguments for invoking getResourceList.
 */
export interface GetResourceListOutputArgs {
    listMode?: pulumi.Input<string>;
    name: pulumi.Input<string>;
    nameIdSeparator?: pulumi.Input<string>;
    org?: pulumi.Input<string>;
    parent?: pulumi.Input<string>;
    resourceType: pulumi.Input<string>;
    vdc?: pulumi.Input<string>;
}
