// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export function getVmGroup(args: GetVmGroupArgs, opts?: pulumi.InvokeOptions): Promise<GetVmGroupResult> {
    if (!opts) {
        opts = {}
    }

    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
    return pulumi.runtime.invoke("vcd:index/getVmGroup:getVmGroup", {
        "name": args.name,
        "providerVdcId": args.providerVdcId,
    }, opts);
}

/**
 * A collection of arguments for invoking getVmGroup.
 */
export interface GetVmGroupArgs {
    name: string;
    providerVdcId: string;
}

/**
 * A collection of values returned by getVmGroup.
 */
export interface GetVmGroupResult {
    readonly clusterMoref: string;
    readonly clusterName: string;
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    readonly name: string;
    readonly namedVmGroupId: string;
    readonly providerVdcId: string;
    readonly vcenterId: string;
}

export function getVmGroupOutput(args: GetVmGroupOutputArgs, opts?: pulumi.InvokeOptions): pulumi.Output<GetVmGroupResult> {
    return pulumi.output(args).apply(a => getVmGroup(a, opts))
}

/**
 * A collection of arguments for invoking getVmGroup.
 */
export interface GetVmGroupOutputArgs {
    name: pulumi.Input<string>;
    providerVdcId: pulumi.Input<string>;
}
